extends: default

ignore: |
  gitops/**/templates/

rules:
  document-start: disable
  line-length:
    max: 160
  truthy:
    check-keys: false  # GitHub Actions uses the `on:` key
  comments:
    min-spaces-from-content: 1
